import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';

// Approved public /llms.txt (Demand Flow, 2026-10-01). Returned byte-for-byte.
const body = "# Dead River Management\n\n> Growth partner for businesses ready to break through the next stage. Dead River builds and manages acquisition, conversion, follow-up, retention, measurement, and strategy as one system. Based in El Paso, Texas; working with growing businesses nationwide. Not Dead River Company (New England fuel), we do not sell fuel.\n\nDead River Management helps accepted businesses generate demand and turn it into revenue. Phone (915) 228-3054. Email brandon@deadrivermanagement.com. Monday to Saturday, 9 to 6 Mountain Time. No street address is published.\n\n## Demand Flow\n- Public offer: **Demand Flow**, **$50,000 in new revenue in 45–60 days**, or service fees refunded + **$500** (ad spend not refunded). Accepted businesses only. Terms updated Sep 29, 2026.\n- Book: https://www.deadrivermanagement.com/book\n- Guarantee terms: https://www.deadrivermanagement.com/legal/guarantee\n\n## Case studies\n- [Parcel Management Group](https://www.deadrivermanagement.com/work/parcel-management-group): 49 Facebook leads in 30 days at $17.70 each.\n- [Total Auto Repair](https://www.deadrivermanagement.com/work/total-auto-repair): From roughly $20K to $100K a month.\n- [Gonzalez & Sons Roofing](https://www.deadrivermanagement.com/work/gonzalez-and-sons-roofing): From around 2 to 8 roofs a month.\n- [The Pipe Whisperers](https://www.deadrivermanagement.com/work/the-pipe-whisperers): From roughly $60K to $250K a year.\n- [Wicked Logistics](https://www.deadrivermanagement.com/work/wicked-logistics): From 1–2 leads a week to 5–6 a day; one lead became a $1.2 million contract.\n- [Only Fish](https://www.deadrivermanagement.com/work/only-fish): New brand launch, logo, site, and social in one direction.\n\n## Free tools\n- [Campaign ROI Calculator](https://www.deadrivermanagement.com/tools/campaign-roi)\n- [Customer Acquisition Cost](https://www.deadrivermanagement.com/tools/customer-acquisition-cost)\n- [Revenue Goal Planner](https://www.deadrivermanagement.com/tools/revenue-goal)\n- [Ad Budget Planner](https://www.deadrivermanagement.com/tools/ad-budget)\n- [Lead Response Scorecard](https://www.deadrivermanagement.com/tools/lead-response)\n- [Growth Readiness Check](https://www.deadrivermanagement.com/tools/growth-readiness)\n- [Website Conversion Review](https://www.deadrivermanagement.com/tools/website-conversion)\n- [SEO Foundations Checklist](https://www.deadrivermanagement.com/tools/seo-foundations)\n- [Search Snippet Preview](https://www.deadrivermanagement.com/tools/search-preview)\n- [Campaign URL Builder](https://www.deadrivermanagement.com/tools/campaign-url)\n\n## Company\n- [About](https://www.deadrivermanagement.com/company)\n- [El Paso, Texas](https://www.deadrivermanagement.com/locations/el-paso)\n- [Contact](https://www.deadrivermanagement.com/book)\n\n";

export const prerender = true;

export const GET: APIRoute = async () => {
  const posts = (await getCollection('blog', ({ data }) => !data.draft)).sort((a, b) => b.data.date.valueOf() - a.data.date.valueOf());
  const articles = '\n## Articles\n' + posts.map((p) => `- [${p.data.title}](https://www.deadrivermanagement.com/marketing-advice/${p.id}): ${p.data.description}`).join('\n') + '\n';
  return new Response(body + articles, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
